use crate::naming::{enum_member, object_key, property_name};
use crate::options::{EnumStyle, NullStyle, Options, TypeStyle};
use crate::typemap;
use convert_case::{Case, Casing};
use gieter_core::emitter::{EmitError, EmitterOutput};
use gieter_core::ir::{Catalog, Column, ColumnType, Domain, Enum, ForeignKey, ScalarType, Table};
use gieter_emit::brand::Brands;
use gieter_emit::declaration::{Declaration, declarations};
use gieter_emit::file::{Files, Fragment, Import};
use gieter_emit::output::{Kind, import_target};
use gieter_emit::writer::Writer;
use std::collections::BTreeSet;

const HEADER: &str = "// Generated by gieter. Do not edit manually.\n\n";
const EMITTER: &str = "typescript";

struct Context<'a> {
    options: &'a Options,
    current_file: &'a str,
    brands: &'a Brands,
}

pub fn render(catalog: &Catalog, options: &Options) -> Result<EmitterOutput, EmitError> {
    let brands = Brands::resolve(catalog, &options.brand);
    let output = &options.output;
    let mut files = Files::new(EMITTER, format_import);

    for (kind, declaration) in declarations(catalog, &brands) {
        files.emit(output, kind, |file| {
            let mut imports = vec![];
            let context = Context {
                options,
                current_file: file,
                brands: &brands,
            };

            let code = match declaration {
                Declaration::Brand(name, scalar) => {
                    render_brand(&context, name, scalar, &mut imports)
                }
                Declaration::Enum(enum_definition) => render_enum(&context, enum_definition),
                Declaration::Composite(composite) => render_object(
                    &context,
                    &composite.name.to_case(Case::Pascal),
                    &composite.fields,
                    &None,
                    &mut imports,
                    None,
                ),
                Declaration::Domain(domain) => render_domain(&context, domain, &mut imports),
                Declaration::Table(table) => render_object(
                    &context,
                    &table.name.to_case(Case::Pascal),
                    &table.columns,
                    &table.comment,
                    &mut imports,
                    Some(table),
                ),
                Declaration::View(view) => render_object(
                    &context,
                    &view.name.to_case(Case::Pascal),
                    &view.columns,
                    &view.comment,
                    &mut imports,
                    None,
                ),
            };

            Fragment { code, imports }
        })?;
    }

    Ok(files.finish(HEADER))
}

fn render_object(
    context: &Context,
    name: &str,
    columns: &[Column],
    comment: &Option<String>,
    imports: &mut Vec<Import>,
    table: Option<&Table>,
) -> String {
    let mut writer = Writer::with_indent(&context.options.indent);

    if context.options.comments
        && let Some(text) = comment
    {
        write_doc(&mut writer, std::slice::from_ref(text));
    }

    let (open, close) = match context.options.type_style {
        TypeStyle::Interface => (format!("export interface {name} {{"), "}"),
        TypeStyle::Type => (format!("export type {name} = {{"), "};"),
    };

    writer.block(&open, close, |writer| {
        for column in columns {
            render_column(context, column, imports, writer, table);
        }
    });

    writer.finish()
}

fn render_column(
    context: &Context,
    column: &Column,
    imports: &mut Vec<Import>,
    writer: &mut Writer,
    table: Option<&Table>,
) {
    let mut doc = vec![];

    if context.options.comments
        && let Some(text) = &column.comment
    {
        doc.push(text.clone());
    }

    if context.options.key_comments
        && let Some(table) = table
    {
        if table.primary_key.iter().any(|pk| pk == &column.name) {
            doc.push("PK".to_string());
        }

        if let Some(reference) = fk_reference(&table.foreign_keys, &column.name) {
            doc.push(format!("FK {reference}"));
        }
    }

    write_doc(writer, &doc);

    let ty = match brand_ty(context, column, table, imports) {
        Some(branded) => branded,
        None => column_ts(context, &column.ty, imports),
    };

    let name = property_name(&column.name, &context.options.property_case);

    let line = match context.options.null_style {
        NullStyle::Union if column.nullable => format!("{name}: {ty} | null;"),
        NullStyle::Optional if column.nullable => format!("{name}?: {ty};"),
        _ => format!("{name}: {ty};"),
    };

    writer.line(&line);
}

/// A `references <schema>.<table>.<column>` note for a column that is part of a foreign
/// key. Columns map to `ref_columns` positionally, so this works for composite keys too.
fn fk_reference(foreign_keys: &[ForeignKey], column: &str) -> Option<String> {
    for foreign_key in foreign_keys {
        if let Some(index) = foreign_key.columns.iter().position(|c| c == column)
            && let Some(ref_column) = foreign_key.ref_columns.get(index)
        {
            let (schema, table) = &foreign_key.ref_table;
            return Some(format!("references {schema}.{table}.{ref_column}"));
        }
    }
    None
}

/// Emit a JSDoc comment: nothing for no lines, a one-liner for a single line, a block otherwise.
fn write_doc(writer: &mut Writer, lines: &[String]) {
    match lines {
        [] => {}
        [single] => writer.line(&format!("/** {single} */")),
        many => {
            writer.line("/**");
            for line in many {
                writer.line(&format!(" * {line}"));
            }
            writer.line(" */");
        }
    }
}

/// The brand type for a column, if it carries one, importing it when the `brands` declarations
/// live in a different file than this column.
fn brand_ty(
    context: &Context,
    column: &Column,
    table: Option<&Table>,
    imports: &mut Vec<Import>,
) -> Option<String> {
    let table = table?;

    let name = context
        .brands
        .brand_of(&table.schema, &table.name, &column.name)?;

    if let Some(target) = import_target(&context.options.output, context.current_file, Kind::Brands)
    {
        imports.push(Import::Named {
            target: target.to_string(),
            symbol: name.to_string(),
        });
    }

    Some(name.to_string())
}

fn format_import(module: &str, symbols: &[&str]) -> String {
    format!(
        "import type {{ {} }} from '{}';",
        symbols.join(", "),
        module_specifier(module)
    )
}

fn module_specifier(file: &str) -> String {
    format!("./{}", file.strip_suffix(".ts").unwrap_or(file))
}

fn column_ts(context: &Context, ty: &ColumnType, imports: &mut Vec<Import>) -> String {
    match ty {
        ColumnType::Scalar(scalar) => {
            let mapped = typemap::resolve(scalar, &context.options.types);
            if let Some(import) = mapped.import {
                imports.push(Import::Raw(import));
            }
            mapped.ts
        }
        ColumnType::Array(inner) => {
            format!("{}[]", column_ts(context, inner, imports))
        }
        ColumnType::Enum { name, .. } => named_type(context, name, Kind::Enums, imports),
        ColumnType::Composite { name, .. } => named_type(context, name, Kind::Composites, imports),
        ColumnType::Domain { name, .. } => named_type(context, name, Kind::Domains, imports),
    }
}

fn named_type(context: &Context, name: &str, kind: Kind, imports: &mut Vec<Import>) -> String {
    let name = name.to_case(Case::Pascal);
    if let Some(target) = import_target(&context.options.output, context.current_file, kind) {
        imports.push(Import::Named {
            target: target.to_string(),
            symbol: name.clone(),
        });
    }
    name
}

fn brand_type(name: &str, base_ts: &str) -> String {
    let mut writer = Writer::new();
    writer.line(&format!(
        "export type {name} = {base_ts} & {{ readonly __brand: '{name}' }};"
    ));
    writer.finish()
}

fn render_brand(
    context: &Context,
    name: &str,
    scalar: &ScalarType,
    imports: &mut Vec<Import>,
) -> String {
    let mapped = typemap::resolve(scalar, &context.options.types);
    if let Some(import) = mapped.import {
        imports.push(Import::Raw(import));
    }
    brand_type(name, &mapped.ts)
}

fn render_domain(context: &Context, domain: &Domain, imports: &mut Vec<Import>) -> String {
    let base_ts = column_ts(context, &domain.base, imports);
    let name = domain.name.to_case(Case::Pascal);
    brand_type(&name, &base_ts)
}

fn render_enum(context: &Context, enum_definition: &Enum) -> String {
    let name = enum_definition.name.to_case(Case::Pascal);

    let mut writer = Writer::with_indent(&context.options.indent);

    match context.options.enum_style {
        EnumStyle::Union => {
            let members: Vec<String> = enum_definition
                .values
                .iter()
                .map(|value| format!("\"{value}\""))
                .collect();
            writer.line(&format!("export type {name} = {};", members.join(" | ")));
        }
        EnumStyle::Enum => {
            writer.block(&format!("export enum {name} {{"), "}", |writer| {
                let mut used: BTreeSet<String> = BTreeSet::new();
                for value in &enum_definition.values {
                    let base = enum_member(value);
                    let mut member = base.clone();
                    let mut suffix = 2;
                    while used.contains(&member) {
                        member = format!("{base}{suffix}");
                        suffix += 1;
                    }
                    used.insert(member.clone());
                    writer.line(&format!("{member} = \"{value}\","));
                }
            });
        }
        EnumStyle::Const => {
            writer.block(
                &format!("export const {name} = {{"),
                "} as const;",
                |writer| {
                    for value in &enum_definition.values {
                        writer.line(&format!("{}: \"{value}\",", object_key(value)));
                    }
                },
            );
            writer.line(&format!(
                "export type {name} = (typeof {name})[keyof typeof {name}];"
            ));
        }
    }

    writer.finish()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::options::TypeOverride;
    use gieter_core::emitter::GeneratedFile;
    use gieter_core::ir::{Composite, Schema};
    use gieter_emit::brand::BrandConfig;
    use gieter_emit::output::Output;
    use std::collections::BTreeMap;
    use std::path::PathBuf;

    fn column(name: &str, ty: ColumnType, nullable: bool) -> Column {
        Column {
            name: name.into(),
            ty,
            nullable,
            comment: None,
        }
    }

    fn table(name: &str, columns: Vec<Column>) -> Table {
        Table {
            name: name.into(),
            schema: "public".into(),
            columns,
            primary_key: vec!["id".into()],
            ..Default::default()
        }
    }

    fn one_schema(tables: Vec<Table>, enums: Vec<Enum>) -> Catalog {
        Catalog {
            schemas: vec![Schema {
                name: "public".into(),
                tables,
                enums,
                ..Default::default()
            }],
        }
    }

    #[test]
    fn const_enum_quotes_labels_that_are_not_valid_identifiers() {
        let catalog = one_schema(
            vec![],
            vec![Enum {
                name: "status".into(),
                schema: "public".into(),
                values: vec![
                    "active".into(),
                    "2fa".into(),
                    "multi word".into(),
                    "has-dash".into(),
                ],
            }],
        );
        let opts = Options {
            enum_style: EnumStyle::Const,
            ..Default::default()
        };
        let contents = &render(&catalog, &opts).unwrap().files[0].contents;

        // Valid identifiers stay bare; everything else is quoted, and the key
        // always mirrors the label so the value and key never diverge.
        assert!(contents.contains("  active: \"active\",\n"));
        assert!(contents.contains("  \"2fa\": \"2fa\",\n"));
        assert!(contents.contains("  \"multi word\": \"multi word\",\n"));
        assert!(contents.contains("  \"has-dash\": \"has-dash\",\n"));
        // The old PascalCased, unquoted (and sometimes invalid) keys are gone.
        assert!(!contents.contains("2Fa"));
        assert!(!contents.contains("MultiWord"));
        assert!(!contents.contains("HasDash"));
    }

    #[test]
    fn enum_style_sanitizes_member_names_and_disambiguates_collisions() {
        let catalog = one_schema(
            vec![],
            vec![Enum {
                name: "status".into(),
                schema: "public".into(),
                values: vec![
                    "active".into(),
                    "2fa".into(),
                    "has-dash".into(),
                    "multi word".into(),
                    "multi-word".into(),
                ],
            }],
        );
        let opts = Options {
            enum_style: EnumStyle::Enum,
            ..Default::default()
        };
        let contents = &render(&catalog, &opts).unwrap().files[0].contents;

        // Valid identifiers are preserved; a leading digit gets a `_` prefix.
        assert!(contents.contains("  active = \"active\",\n"));
        assert!(contents.contains("  _2Fa = \"2fa\",\n"));
        assert!(contents.contains("  HasDash = \"has-dash\",\n"));
        // "multi word" and "multi-word" both PascalCase to MultiWord; the second
        // is disambiguated with a numeric suffix.
        assert!(contents.contains("  MultiWord = \"multi word\",\n"));
        assert!(contents.contains("  MultiWord2 = \"multi-word\",\n"));
    }

    fn branded() -> Options {
        Options {
            brand: BrandConfig {
                enabled: true,
                extra: vec![],
            },
            ..Default::default()
        }
    }

    fn books_with_author_fk() -> Table {
        Table {
            name: "books".into(),
            schema: "public".into(),
            columns: vec![
                column("id", ColumnType::Scalar(ScalarType::Int32), false),
                column("author_id", ColumnType::Scalar(ScalarType::Int32), false),
            ],
            primary_key: vec!["id".into()],
            foreign_keys: vec![ForeignKey {
                name: "books_author_fk".into(),
                columns: vec!["author_id".into()],
                ref_table: ("public".into(), "authors".into()),
                ref_columns: vec!["id".into()],
            }],
            comment: None,
        }
    }

    #[test]
    fn renders_enums_and_a_table_into_one_file_with_defaults() {
        let catalog = one_schema(
            vec![table(
                "books",
                vec![
                    column("id", ColumnType::Scalar(ScalarType::Int32), false),
                    column(
                        "tags",
                        ColumnType::Array(Box::new(ColumnType::Scalar(ScalarType::Text {
                            max_len: None,
                        }))),
                        true,
                    ),
                    column(
                        "vibe",
                        ColumnType::Enum {
                            schema: "public".into(),
                            name: "mood".into(),
                        },
                        true,
                    ),
                ],
            )],
            vec![Enum {
                name: "mood".into(),
                schema: "public".into(),
                values: vec!["happy".into(), "sad".into()],
            }],
        );

        let output = render(&catalog, &Options::default()).unwrap();
        assert_eq!(output.files.len(), 1);
        assert_eq!(output.files[0].path, PathBuf::from("index.ts"));
        assert_eq!(
            output.files[0].contents,
            "// Generated by gieter. Do not edit manually.\n\n\
             export type Mood = \"happy\" | \"sad\";\n\n\
             export interface Books {\n  \
             /** PK */\n  \
             id: number;\n  \
             tags: string[] | null;\n  \
             vibe: Mood | null;\n\
             }\n"
        );
    }

    #[test]
    fn foreign_key_columns_get_a_reference_comment() {
        let catalog = one_schema(vec![books_with_author_fk()], vec![]);
        let output = render(&catalog, &Options::default()).unwrap();
        assert!(
            output.files[0]
                .contents
                .contains("/** FK references public.authors.id */")
        );
    }

    #[test]
    fn primary_key_columns_get_a_pk_comment() {
        let catalog = one_schema(
            vec![table(
                "books",
                vec![column("id", ColumnType::Scalar(ScalarType::Int32), false)],
            )],
            vec![],
        );
        let output = render(&catalog, &Options::default()).unwrap();
        assert!(output.files[0].contents.contains("/** PK */"));
    }

    #[test]
    fn key_comments_can_be_disabled() {
        let catalog = one_schema(vec![books_with_author_fk()], vec![]);
        let options = Options {
            key_comments: false,
            ..Default::default()
        };
        let output = render(&catalog, &options).unwrap();
        let contents = &output.files[0].contents;
        assert!(!contents.contains("PK"));
        assert!(!contents.contains("FK references"));
    }

    #[test]
    fn a_commented_foreign_key_column_gets_a_multi_line_doc() {
        let mut books = books_with_author_fk();
        books.columns[1].comment = Some("the writer".into());
        let output = render(&one_schema(vec![books], vec![]), &Options::default()).unwrap();
        let contents = &output.files[0].contents;
        assert!(contents.contains(" * the writer"));
        assert!(contents.contains(" * FK references public.authors.id"));
    }

    #[test]
    fn a_composite_foreign_key_references_columns_positionally() {
        let line_item = Table {
            name: "line_item".into(),
            schema: "public".into(),
            columns: vec![
                column("order_id", ColumnType::Scalar(ScalarType::Int32), false),
                column(
                    "sku",
                    ColumnType::Scalar(ScalarType::Text { max_len: None }),
                    false,
                ),
            ],
            primary_key: vec![],
            foreign_keys: vec![ForeignKey {
                name: "line_item_fk".into(),
                columns: vec!["order_id".into(), "sku".into()],
                ref_table: ("public".into(), "order_sku".into()),
                ref_columns: vec!["oid".into(), "code".into()],
            }],
            comment: None,
        };
        let output = render(&one_schema(vec![line_item], vec![]), &Options::default()).unwrap();
        let contents = &output.files[0].contents;
        assert!(contents.contains("/** FK references public.order_sku.oid */"));
        assert!(contents.contains("/** FK references public.order_sku.code */"));
    }

    #[test]
    fn a_configured_indent_is_applied() {
        let catalog = one_schema(
            vec![table(
                "books",
                vec![column("id", ColumnType::Scalar(ScalarType::Int32), false)],
            )],
            vec![],
        );
        let options = Options {
            indent: "\t".into(),
            ..Default::default()
        };
        let output = render(&catalog, &options).unwrap();
        assert!(output.files[0].contents.contains("\tid: number;"));
    }

    #[test]
    fn splits_kinds_across_files_and_hoists_a_scalar_import() {
        let catalog = one_schema(
            vec![table(
                "books",
                vec![column("id", ColumnType::Scalar(ScalarType::Uuid), false)],
            )],
            vec![Enum {
                name: "mood".into(),
                schema: "public".into(),
                values: vec!["happy".into()],
            }],
        );

        let options = Options {
            output: split(&[("enums", "enums.ts"), ("default", "db.ts")]),
            types: BTreeMap::from([(
                "uuid".to_string(),
                TypeOverride {
                    ts: "UUID".into(),
                    import: Some("import type { UUID } from './uuid';".into()),
                },
            )]),
            ..Default::default()
        };

        let output = render(&catalog, &options).unwrap();
        let names: Vec<&str> = output
            .files
            .iter()
            .map(|file| file.path.to_str().unwrap())
            .collect();
        assert_eq!(names, ["db.ts", "enums.ts"]);

        let db = output
            .files
            .iter()
            .find(|file| file.path.to_str() == Some("db.ts"))
            .unwrap();
        assert!(db.contents.contains("import type { UUID } from './uuid';"));
        assert!(db.contents.contains("id: UUID;"));
    }

    #[test]
    fn an_unmapped_kind_without_a_default_is_an_error() {
        let catalog = one_schema(
            vec![table(
                "books",
                vec![column("id", ColumnType::Scalar(ScalarType::Int32), false)],
            )],
            vec![],
        );

        let options = Options {
            output: split(&[("enums", "enums.ts")]),
            ..Default::default()
        };

        assert!(render(&catalog, &options).is_err());
    }

    #[test]
    fn branding_emits_brand_types_and_references_them_in_one_file() {
        let authors = table(
            "authors",
            vec![column("id", ColumnType::Scalar(ScalarType::Int32), false)],
        );
        let catalog = one_schema(vec![authors, books_with_author_fk()], vec![]);

        let output = render(&catalog, &branded()).unwrap();
        assert_eq!(output.files.len(), 1);
        let contents = &output.files[0].contents;
        assert!(
            contents
                .contains("export type AuthorsId = number & { readonly __brand: 'AuthorsId' };")
        );
        assert!(
            contents.contains("export type BooksId = number & { readonly __brand: 'BooksId' };")
        );
        assert!(contents.contains("id: BooksId;"));
        assert!(contents.contains("author_id: AuthorsId;"));
        // brands share the file, so no import is generated.
        assert!(!contents.contains("import type"));
    }

    #[test]
    fn branding_imports_brand_types_when_split_into_another_file() {
        let catalog = one_schema(
            vec![table(
                "books",
                vec![column("id", ColumnType::Scalar(ScalarType::Int32), false)],
            )],
            vec![],
        );

        let options = Options {
            brand: BrandConfig {
                enabled: true,
                extra: vec![],
            },
            output: split(&[("tables", "db.ts"), ("brands", "brands.ts")]),
            ..Default::default()
        };

        let output = render(&catalog, &options).unwrap();
        let db = output
            .files
            .iter()
            .find(|file| file.path.to_str() == Some("db.ts"))
            .unwrap();
        assert!(
            db.contents
                .contains("import type { BooksId } from './brands';")
        );
        assert!(db.contents.contains("id: BooksId;"));

        let brands = output
            .files
            .iter()
            .find(|file| file.path.to_str() == Some("brands.ts"))
            .unwrap();
        assert!(
            brands
                .contents
                .contains("export type BooksId = number & { readonly __brand: 'BooksId' };")
        );
    }

    #[test]
    fn brand_imports_from_the_same_file_merge_into_one_line() {
        let authors = table(
            "authors",
            vec![column("id", ColumnType::Scalar(ScalarType::Int32), false)],
        );
        let catalog = one_schema(vec![authors, books_with_author_fk()], vec![]);

        let options = Options {
            brand: BrandConfig {
                enabled: true,
                extra: vec![],
            },
            output: split(&[("tables", "db.ts"), ("brands", "brands.ts")]),
            ..Default::default()
        };

        let output = render(&catalog, &options).unwrap();
        let db = file(&output, "db.ts");

        // Both AuthorsId and BooksId come from ./brands: one merged, sorted line.
        assert!(
            db.contents
                .contains("import type { AuthorsId, BooksId } from './brands';")
        );
        assert_eq!(db.contents.matches("from './brands'").count(), 1);
    }

    fn one_schema_with(schema: Schema) -> Catalog {
        Catalog {
            schemas: vec![schema],
        }
    }

    /// Build a split `Output` from `(kind, file)` pairs via the shared parser.
    fn split(pairs: &[(&str, &str)]) -> Output {
        let body = pairs
            .iter()
            .map(|(kind, file)| format!("{kind} = \"{file}\""))
            .collect::<Vec<_>>()
            .join("\n");
        toml::from_str(&body).expect("valid output split")
    }

    /// Output split so tables, enums, composites and domains each land in their own file.
    fn split_by_kind() -> Output {
        split(&[
            ("tables", "tables.ts"),
            ("enums", "enums.ts"),
            ("composites", "composites.ts"),
            ("domains", "domains.ts"),
        ])
    }

    fn file<'a>(output: &'a EmitterOutput, name: &str) -> &'a GeneratedFile {
        output
            .files
            .iter()
            .find(|file| file.path.to_str() == Some(name))
            .unwrap_or_else(|| panic!("expected a file named {name}"))
    }

    #[test]
    fn a_column_referencing_an_enum_in_another_file_imports_it() {
        let catalog = one_schema(
            vec![table(
                "books",
                vec![column(
                    "vibe",
                    ColumnType::Enum {
                        schema: "public".into(),
                        name: "mood".into(),
                    },
                    false,
                )],
            )],
            vec![Enum {
                name: "mood".into(),
                schema: "public".into(),
                values: vec!["happy".into(), "sad".into()],
            }],
        );

        let options = Options {
            output: split_by_kind(),
            ..Default::default()
        };

        let output = render(&catalog, &options).unwrap();
        assert!(
            file(&output, "tables.ts")
                .contents
                .contains("import type { Mood } from './enums';")
        );
    }

    #[test]
    fn a_column_referencing_a_composite_in_another_file_imports_it() {
        let catalog = one_schema_with(Schema {
            name: "public".into(),
            tables: vec![Table {
                name: "people".into(),
                schema: "public".into(),
                columns: vec![column(
                    "home",
                    ColumnType::Composite {
                        schema: "public".into(),
                        name: "address".into(),
                    },
                    false,
                )],
                primary_key: vec![],
                ..Default::default()
            }],
            composites: vec![Composite {
                name: "address".into(),
                schema: "public".into(),
                fields: vec![column(
                    "street",
                    ColumnType::Scalar(ScalarType::Text { max_len: None }),
                    true,
                )],
            }],
            ..Default::default()
        });

        let options = Options {
            output: split_by_kind(),
            ..Default::default()
        };

        let output = render(&catalog, &options).unwrap();
        assert!(
            file(&output, "tables.ts")
                .contents
                .contains("import type { Address } from './composites';")
        );
    }

    #[test]
    fn a_column_referencing_a_domain_in_another_file_imports_it() {
        let catalog = one_schema_with(Schema {
            name: "public".into(),
            tables: vec![Table {
                name: "people".into(),
                schema: "public".into(),
                columns: vec![column(
                    "contact",
                    ColumnType::Domain {
                        schema: "public".into(),
                        name: "email".into(),
                    },
                    false,
                )],
                primary_key: vec![],
                ..Default::default()
            }],
            domains: vec![Domain {
                name: "email".into(),
                schema: "public".into(),
                base: ColumnType::Scalar(ScalarType::Text { max_len: None }),
                not_null: false,
                default: None,
            }],
            ..Default::default()
        });

        let options = Options {
            output: split_by_kind(),
            ..Default::default()
        };

        let output = render(&catalog, &options).unwrap();
        assert!(
            file(&output, "tables.ts")
                .contents
                .contains("import type { Email } from './domains';")
        );
    }

    #[test]
    fn an_array_of_an_enum_in_another_file_still_imports_it() {
        let catalog = one_schema(
            vec![table(
                "books",
                vec![column(
                    "vibes",
                    ColumnType::Array(Box::new(ColumnType::Enum {
                        schema: "public".into(),
                        name: "mood".into(),
                    })),
                    false,
                )],
            )],
            vec![Enum {
                name: "mood".into(),
                schema: "public".into(),
                values: vec!["happy".into()],
            }],
        );

        let options = Options {
            output: split_by_kind(),
            ..Default::default()
        };

        let output = render(&catalog, &options).unwrap();
        let tables = file(&output, "tables.ts");
        assert!(
            tables
                .contents
                .contains("import type { Mood } from './enums';")
        );
        assert!(tables.contents.contains("vibes: Mood[];"));
    }

    #[test]
    fn a_type_referenced_in_the_same_file_is_not_imported() {
        let catalog = one_schema(
            vec![table(
                "books",
                vec![column(
                    "vibe",
                    ColumnType::Enum {
                        schema: "public".into(),
                        name: "mood".into(),
                    },
                    false,
                )],
            )],
            vec![Enum {
                name: "mood".into(),
                schema: "public".into(),
                values: vec!["happy".into()],
            }],
        );

        // Single-file output: the enum and the table share a file, so no self-import.
        let output = render(&catalog, &Options::default()).unwrap();
        assert!(!output.files[0].contents.contains("import type { Mood }"));
    }

    #[test]
    fn renders_a_composite_type_as_an_interface() {
        let catalog = one_schema_with(Schema {
            name: "public".into(),
            composites: vec![Composite {
                name: "address".into(),
                schema: "public".into(),
                fields: vec![
                    column(
                        "street",
                        ColumnType::Scalar(ScalarType::Text { max_len: None }),
                        true,
                    ),
                    column("number", ColumnType::Scalar(ScalarType::Int32), true),
                ],
            }],
            ..Default::default()
        });

        let contents = &render(&catalog, &Options::default()).unwrap().files[0].contents;
        assert!(contents.contains("export interface Address {"));
        assert!(contents.contains("street: string | null;"));
        assert!(contents.contains("number: number | null;"));
    }

    #[test]
    fn renders_a_domain_type_as_a_brand() {
        let catalog = one_schema_with(Schema {
            name: "public".into(),
            domains: vec![Domain {
                name: "email".into(),
                schema: "public".into(),
                base: ColumnType::Scalar(ScalarType::Text { max_len: None }),
                not_null: false,
                default: None,
            }],
            ..Default::default()
        });

        let contents = &render(&catalog, &Options::default()).unwrap().files[0].contents;
        assert!(contents.contains("export type Email = string & { readonly __brand: 'Email' };"));
    }

    #[test]
    fn columns_reference_composite_and_domain_types_by_name() {
        let catalog = one_schema_with(Schema {
            name: "public".into(),
            tables: vec![Table {
                name: "people".into(),
                schema: "public".into(),
                columns: vec![
                    column(
                        "home",
                        ColumnType::Composite {
                            schema: "public".into(),
                            name: "address".into(),
                        },
                        true,
                    ),
                    column(
                        "contact",
                        ColumnType::Domain {
                            schema: "public".into(),
                            name: "email".into(),
                        },
                        true,
                    ),
                ],
                primary_key: vec![],
                ..Default::default()
            }],
            ..Default::default()
        });

        let contents = &render(&catalog, &Options::default()).unwrap().files[0].contents;
        assert!(contents.contains("home: Address | null;"));
        assert!(contents.contains("contact: Email | null;"));
    }

    #[test]
    fn a_domain_over_an_overridden_scalar_wraps_it_and_hoists_the_import() {
        let catalog = one_schema_with(Schema {
            name: "public".into(),
            domains: vec![Domain {
                name: "account_id".into(),
                schema: "public".into(),
                base: ColumnType::Scalar(ScalarType::Uuid),
                not_null: false,
                default: None,
            }],
            ..Default::default()
        });

        let options = Options {
            types: BTreeMap::from([(
                "uuid".to_string(),
                TypeOverride {
                    ts: "UUID".into(),
                    import: Some("import type { UUID } from './uuid';".into()),
                },
            )]),
            ..Default::default()
        };

        let contents = &render(&catalog, &options).unwrap().files[0].contents;
        assert!(contents.contains("import type { UUID } from './uuid';"));
        assert!(
            contents.contains("export type AccountId = UUID & { readonly __brand: 'AccountId' };")
        );
    }
}
